# -*- coding: utf-8 -*-
"""alx-crash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cwQZnO7ptGCjlmB4A7URojF5FcgDvfR
"""

initial_var = 8
even_num = initial_var

print(initial_var)

from re import X
x = 13
y = 13

print(f"memory address of x:{hex(id(x))}")
print(f"memory address of y: {hex(id(y))}")

# PEP 8: Python Enhancement Proposal 8: the style guide for writing python code.

# Camel case
thisIsMyVar = 5
# Pascal case
ThisIsMyVar = 7.5
# Snake case
this_is_my_var = 10.5

""" 5 primitive variable types used in Python:
1. integers
2. floats
3. strings
4. booleans
5. complex numbers
"""

original_string = "Hello"
modified_string = original_string + ", Python!"

print(modified_string)
type(modified_string)

complex_num = 2 + 5j
type(complex_num)

""" specifying, converting and casting data types:
1. Specify: Focuses on declaring the type explicitly at the variable's creation.
2. Convert: Involves changing the variable's type implicitly during data processing or variable manipulation.
3. Cast: Similar to conversion but implies a more explicit or intentional change.
"""

# 1:
integer_variable = int(24)
float_var = float(3.14)
string_var = str(12345)

print(f"integer variable: {integer_variable}")
print(f"float variable: {float_var}")
print(f"string variable: {string_var}")

print()

#2:
int1 = 5
int2 = 10
ans = int2/int1

print(int1, ":", type(int1))
print(int2, ":", type(int2))
print(f"{ans} : {type(ans)}")

print()

#3: Type casting could result in data loss
float_result = float("42")
integer_from_float_result = int(float_result)

print(float_result, ":", type(float_result))
print(f"{integer_from_float_result} : {type(integer_from_float_result)}")

int_result = int("3.14")

# The error occurs because you're trying to convert a string with a decimal point ('3.14') directly to an integer using int().
# Python's int() function can only convert strings that represent whole numbers.
# To fix this, you should first convert the string to a float, and then convert that float to an integer.

float_output = float("3.14")
int_output = int(float_output)

print(type(int_output))

var_a = 5.67
var_b = "123"

float_var_b = float(var_b)
print(float_var_b)

result = var_a + float_var_b
print(result)

mixed_var = "42.42"

float_mixed_var = float(mixed_var)
int_mixed_var = int(float_mixed_var)

print(f"{float_mixed_var} : {type(float_mixed_var)}")
print(f"{int_mixed_var} : {type(int_mixed_var)}")

total_amount = 42.56
total_amount_in_cents = int(total_amount * 100)

print(total_amount_in_cents)

"""**Intro to Strings.**"""

# Positive Indexing

my_string = "Hello, World!"

first_char = my_string[0]
second_char = my_string[1]
last_char = my_string[12]

print("Positive indexing:")
print("First character:", first_char)
print("Second character:", second_char)
print("Last character:", last_char)

# Negative Indexing

last_char_negative = my_string[-1]
second_last_char = my_string[-2]
first_char_negative = my_string[-12]

print("\nNegative indexing:")
print("Last character:", last_char_negative)
print("Second last character:", second_last_char)
print("First character:", first_char_negative)

# Immutable: strings in python are immutable.

original_string = "Hello, World"
original_string[0] = 'h'

# Aany operation that seems to modify a string actually creates a new string with the modified content.

original_string = "Hello"
new_string = original_string + ", World!"

print(new_string)

# Not modification, but rebinding the variable to a new string object.

original_string = "Hello, World!"
original_string = "hello. World?"

print(original_string)

"""**Special Characters.**"""

# newline (\n)
print("Hello, \nWorld!")

# tab (\t)
print("\tHello, World!")

# Backlash (\\) - an escape character
print("This is a backlash: \\")

# single quote (\')
print('He said, \'Hello!\'')

# double quote (\")
print("She exclaimed, \"Wow!\"")

# carriage return (\r)
print("Overwrite\rThis text.")

print("Hello World !\rGood")

# backspace (\b)
print("Remove\b This")

# alert (\a)
print("This is an alert!\a")

# octal representation (\ooo)
print("Octal representation: \110")

# hexadecimal representation (\xhh)
print("Hexadecimal representation: \x48")

"""**Usage of Special Characters (Practice)**"""

challenge_string = "PythonIsAwesome!"

print(challenge_string[2])
print(challenge_string[-1])
print(challenge_string[6:11])

string1 = "Programming"
string2 = " is fun!"

result = (string1 + " " + string2)
print(result)

multiline_text = '''Fawaz, Age: 22\nThis is a multiline string
Name:\tFawaz
This is a backlash: \\
He said \'Hello!'\
She exclaimed \"Wow!"\
Overwrite\rThis text.
Removek\b this.
'''

print(multiline_text)

"""## **`String Manipulation`**"""

# Concatenation

string1 = "Hello"
string2 = "World"
result = string1 + " " + string2
print(result)

# Replication

original_string = "python"
replicated_string = original_string * 3
print(replicated_string)

# Slicing

text = "Python is amazing"
substring = text[0:6]
print(substring)

# The character at index -1 is automatically excluded.

text = "Python is amazing"
substring = text[-7:-1]
print(substring)

text = "Python is amazing"
substring = text[-7:]
print(substring)

#upper()

text = "    Python is superb!    "

uppercase_text = text.upper()
print(uppercase_text)

lowercase_text = text.lower()
print(lowercase_text)

capitalised_text = text.capitalize()
print(capitalised_text)

trimmed_input = text.strip()
print(trimmed_input)

modified_text = text.replace("Python", "Javascript")
print(modified_text)

index = text.find("superb")
print(index)

"""**Quick Exercise**"""

num1 = 15
num2 = 7
sum = num1 + num2
difference = num1 - num2
product = num1 * num2
division = float(num1/num2)

print(sum)
print(difference)
print(product)
print(division)

first_name = "Fawaz"
last_name = "Bello"

full_name = first_name + " " + last_name
print(full_name.upper())

num_of_books = "3"
books_read = int(num_of_books)

avg_books_read_per_week = books_read/4
print(avg_books_read_per_week)

name = "John Doe"
age = 25
height = 1.75
weight = 68.5

BMI = weight/(height ** 2)
print(BMI)

product_name = "Widget XYZ"
initial_quantity = 100
price_per_unit = 12.50
discount_percentage = 0.15

initial_stock_value = initial_quantity * price_per_unit
discounted_value = initial_stock_value - (initial_stock_value * discount_percentage)
updated_stock_quantity = initial_quantity + 30

print(initial_stock_value)
print(discounted_value)
print(updated_stock_quantity)

growth_rate = 2.5
forest_region = "Amazon"

formatted_string = "The annual growth rate of trees in the {forest} forest is {growth}%".format(forest = forest_region, growth = growth_rate)
print(formatted_string)

sfm_concept = "Sustainable Forest Management"
biodiversity_importance = "maintaining biodiversity"

print(f"{sfm_concept} is crucial for {biodiversity_importance}")

----

# sick day log

symptoms = ["Headache", "Body Pain", "Fatigue", "High Fever", "Chills"]
print(f"Current status: {symptoms}")

print()

for sickness in symptoms:
    print(f"Fighting {sickness}... Cleared!")

print()
print("System recovering... Ready for tomorrow.")
